version: "3.5"

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack-server
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - balusoft
    volumes:
      - redis:/redis/data


networks:
  balusoft:
    name: balusoft-network

volumes:
  redis:
    driver: local