version: '3.4'

services:
  distributedcacheexample:
    image: ${DOCKER_REGISTRY-}distributedcacheexample
    build:
      context: .
      dockerfile: DistributedCacheExample/Dockerfile
    ports:
      - 7198:443
      - 5106:80      
    networks:
      - balusoft

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack-server
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - balusoft
    volumes:
      - redis:/redis/data

networks:
  balusoft:
    name: balusoft-network

volumes:
  redis:
    driver: local
