{
 "title": "ASP.NET Core Build 2023",
 "description": "ASP.NET Core metrics from OpenTelemetry NuGet",
 "tags": [
  "dotnet",
  "prometheus",
  "aspnetcore"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "exported_job",
    "label": "Job",
    "query": {
     "query": "label_values(ec_System_Net_Http_current_requests,exported_job)"
    }
   },
   {
    "name": "exported_instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ec_System_Net_Http_current_requests{exported_job=~\"$exported_job\"},exported_instance)"
    }
   },
   { "name": "prometheus_source", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", http_status_code=~\"4..|5..\"}[5m])) or vector(0) / sum(rate(http_server_duration_milliseconds_count{exported_job=\"$job\", exported_instance=\"$exported_instance\"}[5m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", http_status_code=~\"4..\"}[5m])) or vector(0) / sum(rate(http_server_duration_milliseconds_count{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", http_status_code=~\"5..\"}[5m])) or vector(0) / sum(rate(http_server_duration_milliseconds_count{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(ec_Microsoft_AspNetCore_Server_Kestrel_current_connections{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum(ec_System_Net_Http_current_requests{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Secured",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (scheme) (\r\n    max_over_time(http_server_duration_milliseconds_count{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[$__rate_interval])\r\n  )",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "Requests HTTP Protocol",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (protocol) (\r\n    max_over_time(http_server_duration_milliseconds_count{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[$__rate_interval])\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Top 10 Requested Endpoints",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "  topk(10,\r\n  sum by (http_route, http_method, method_route) (\r\n    label_join(max_over_time(http_server_duration_milliseconds_count{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", http_route!=\"\"}[$__rate_interval]), \"method_route\", \" \", \"http_method\", \"http_route\")\r\n  ))",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}