{
 "title": "ASP.NET OTEL (OpenTelemetry) Metrics",
 "description": "Shows ASP.NET (Core/5/6/7) metrics from OpenTelemetry NuGet",
 "tags": [
  "dotnet",
  "opentelemetry",
  "otel",
  "prometheus",
  "process",
  "runtime",
  "httpclient",
  "aspnetcore"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "exported_job",
    "label": "Job",
    "query": {
     "query": "label_values(process_runtime_dotnet_gc_collections_count_total,exported_job)"
    }
   },
   {
    "name": "exported_instance",
    "label": "Instance",
    "query": {
     "query": "label_values(process_runtime_dotnet_gc_collections_count_total{exported_job=~\"$exported_job\"},exported_instance)"
    }
   },
   {
    "name": "http_client_peer_name",
    "label": "HTTP Client Pear Name",
    "query": {
     "query": "label_values(http_client_duration_milliseconds_bucket{exported_job=~\"$exported_job\",exported_instance=~\"$exported_instance\"},net_peer_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_time_seconds_total{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_memory_usage_bytes{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[$__rate_interval])",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(process_threads{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[$__rate_interval])",
     "legendFormat": "Threads"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "General Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_gc_committed_memory_size_bytes{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])",
     "legendFormat": "Committed Memory Size"
    },
    {
     "expr": "max_over_time(process_runtime_dotnet_gc_objects_size_bytes{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])",
     "legendFormat": "Objects Size"
    },
    {
     "expr": "irate(process_runtime_dotnet_gc_allocations_size_bytes_total{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])",
     "legendFormat": "Allocations Size"
    }
   ]
  },
  {
   "title": "Heap Generations (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_gc_heap_size_bytes{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Fragmentation (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_gc_heap_fragmentation_size_bytes{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Collections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(process_runtime_dotnet_gc_collections_count_total{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(process_runtime_dotnet_exceptions_count_total{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])",
     "legendFormat": "Exceptions"
    }
   ]
  },
  {
   "title": "ThreadPool Threads",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_thread_pool_threads_count{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[$__rate_interval])",
     "legendFormat": "ThreadPool Threads"
    }
   ]
  },
  {
   "title": "ThreadPool Threads Queue Length",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_thread_pool_queue_length{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[$__rate_interval])",
     "legendFormat": "ThreadPool Threads Queue Length"
    }
   ]
  },
  { "title": "HTTP Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Responses Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_duration_ms_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by(le) (rate(http_server_duration_ms_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m])))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", http_status_code!~\"2..\"}[5m])) or vector(0) / sum(rate(http_server_duration_milliseconds_count{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", http_status_code=~\"4..\"}[5m])) or vector(0) / sum(rate(http_server_duration_milliseconds_count{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", http_status_code=~\"5..\"}[5m])) or vector(0) / sum(rate(http_server_duration_milliseconds_count{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "HTTP Client ($http_client_peer_name)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "repeat": "http_client_peer_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(http_client_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", net_peer_name=\"$http_client_peer_name\"}[5m])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(http_client_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", net_peer_name=\"$http_client_peer_name\"}[5m])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(http_client_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", net_peer_name=\"$http_client_peer_name\"}[5m])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(http_client_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", net_peer_name=\"$http_client_peer_name\"}[5m])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.98, sum by(le) (rate(http_client_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", net_peer_name=\"$http_client_peer_name\"}[5m])))",
       "legendFormat": "p98"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(http_client_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", net_peer_name=\"$http_client_peer_name\"}[5m])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.999, sum by(le) (rate(http_client_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", net_peer_name=\"$http_client_peer_name\"}[5m])))",
       "legendFormat": "p99.9"
      }
     ]
    },
    {
     "title": "Errors Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", net_peer_name=\"$http_client_peer_name\", http_status_code!~\"2..\"}[5m])) or vector(0) / sum(rate(http_client_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", net_peer_name=\"$http_client_peer_name\"}[5m]))",
       "legendFormat": "All"
      },
      {
       "expr": "sum(rate(http_client_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", net_peer_name=\"$http_client_peer_name\", http_status_code=~\"4..\"}[5m])) or vector(0) / sum(rate(http_client_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", net_peer_name=\"$http_client_peer_name\"}[5m]))",
       "legendFormat": "4XX"
      },
      {
       "expr": "sum(rate(http_client_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", net_peer_name=\"$http_client_peer_name\", http_status_code=~\"5..\"}[5m])) or vector(0) / sum(rate(http_client_duration_milliseconds_bucket{exported_job=\"$exported_job\", exported_instance=\"$exported_instance\", net_peer_name=\"$http_client_peer_name\"}[5m]))",
       "legendFormat": "5XX"
      }
     ]
    }
   ]
  }
 ]
}