@host = http://localhost:5051


### Create Payment
POST {{host}}/api/payment
Content-Type: application/json

{
    "tokenCard": "tok_1J4Z3n2eZvKYlo2C0X2X2X2X",
    "amount": 1000,
    "currency": "usd",
    "cardHolderName": "John Doe",
    "cardHolderEmail": "john.doe@mail.com"
}

### Get Payment
GET {{host}}/api/payment/status/43c34018-6446-420a-8c8a-0c29607d632b
Content-Type: application/json